"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0VbRms2Lb7H
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useState } from "react";

export default function BlinkTemplate() {
  const [image, setImage] = useState<string | null>(null);
  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setImage(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };
  return (
    // <div className="grid md:grid-cols-2 gap-6 items-center">
    <div>
      <div className="border border-black p-4 h-[300px]">
        <Card className="">
          <CardHeader>
            <CardTitle>Create Your Order</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2">
              {image ? (
                <img
                  src={image}
                  alt="Product image"
                  className="aspect-square w-full rounded-md object-cover"
                  width={300}
                  height={300}
                />
              ) : (
                <img
                  src="/placeholder.svg"
                  alt="Product image"
                  className="aspect-square w-full rounded-md object-cover"
                  width={300}
                  height={300}
                />
              )}
              <Button
                variant="outline"
                size="sm"
                className="justify-center"
                onClick={() => document.getElementById("fileInput")?.click()}
              >
                <UploadIcon className="h-4 w-4 mr-2" />
                Upload Image
              </Button>
              <input
                type="file"
                id="fileInput"
                accept="image/*"
                onChange={handleImageUpload}
                style={{ display: "none" }}
              />
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-none border-none">
          <CardHeader className="border-t">
            <Input
              id="name"
              placeholder="Product Name"
              className="text-2xl font-bold bg-transparent border-0 focus:ring-0"
            />
          </CardHeader>
          <CardContent>
            <form className="grid gap-4">
              <div className="grid gap-2">
                <Input
                  id="title"
                  placeholder="Product Title"
                  className="text-2xl font-bold bg-transparent border-0 focus:ring-0"
                />
              </div>
              <div className="grid gap-2">
                <Textarea
                  id="description"
                  placeholder="Enter product description"
                  className="min-h-[100px] bg-transparent border-0 focus:ring-0"
                />
              </div>
              <div className="grid gap-2">
                <Input
                  id="label"
                  placeholder="Label"
                  className="bg-transparent border-0 focus:ring-0"
                />
              </div>
              <div className="grid gap-2">
                <Input
                  id="price"
                  type="number"
                  placeholder="Price"
                  className="bg-transparent border-0 focus:ring-0"
                />
              </div>
              <Button type="submit" className="justify-center">
                <PlusIcon className="h-4 w-4 mr-2" />
                Add Product
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}

function UploadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}
